openapi: 3.0.0
info:
  title: 视频生成任务
  version: '1.0'
  description: 视频生成任务API
servers: []
paths:
  /task:
    get:
      summary: 获取任务列表
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/task.v1.yaml
      description: 返回任务列表.
    post:
      summary: 创建视频生成任务
      responses:
        '200':
          description: 任务创建成功
          content:
            application/json:
              schema:
                $ref: ../common/models/task.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: 创建一个视频生成任务.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/task_config.v1.yaml
    parameters: []
  '/task/{task_id}':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
        schema:
          type: number
        description: task id
    get:
      summary: 返回task对象.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/task.v1.yaml
        '404':
          description: 任务没找到
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: 返回task对象.
    post:
      summary: 重新生成视频
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/task.v1.yaml
        '404':
          description: 任务未找到
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      description: 重新生成视频. 请在更新了summary后者timeline之后重新生成视频.
    delete:
      summary: 终止任务
      responses:
        '200':
          description: OK
      description: 终止任务.
  '/task/{task_id}/summary':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
    get:
      summary: 获取当前任务的summary.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/summary.v1.yaml
      description: 获取当前任务的summary.
    post:
      summary: 更新当前任务的文章摘要.
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: ../common/models/summary.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/summary.v1.yaml
      description: '更新当前任务的文章摘要. 请注意本操作会更新tts结果, 所以可能会有1分钟左右的response时间, 更新完摘要后timeline会有改变, 请再次请求/task/{task_id}/timeline来获取最新timeline.'
  '/task/{task_id}/timeline':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
    get:
      summary: 获取任务时间轴.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/timeline.v1.yaml
      description: 获取任务时间轴.
    post:
      summary: 更新任务时间轴.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/timeline.v1.yaml
      description: 更新任务时间轴.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/timeline.v1.yaml
components:
  schemas: {}
  securitySchemes: {}
