openapi: 3.0.0
info:
  title: 视频生成任务
  version: '1.0'
  description: 视频生成任务API
servers:
  - url: 'http://vidpress_api_server/v1'
    description: ''
paths:
  /task:
    get:
      summary: 获取任务列表
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paged_tasks'
      description: 返回任务列表.
      parameters:
        - schema:
            type: number
          in: query
          name: page
          description: 'page number, 20 per page'
        - schema:
            type: string
          in: query
          name: task_ids
          description: 'comma seperated task ids, e.g. 1,2,3'
    post:
      summary: 创建视频生成任务
      responses:
        '200':
          description: 任务创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      description: "创建一个视频生成任务. 配置中支持callback_url, 在任务有任何更新的时候request该url; 支持设定任务优先级, 3为普通优先级, 2为高优先级. 原则上支持1和0, 若非必要请勿占用. \n创建视频任务支持不提供news_url, 这样会创建一个空任务, 请通过task upload接口上传所需media, 然后call alignment接口来对齐媒体和文字并生成视频"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task_config'
    parameters: []
  '/task/{task_id}':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
        schema:
          type: number
        description: task id
    get:
      summary: 返回task对象.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: 任务没找到
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      description: 返回task对象.
    post:
      summary: 重新生成视频
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: 任务未找到
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      description: 重新生成视频. 请在更新了summary后者timeline之后重新生成视频. 支持跟新task_config来更改任务优先级
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task_config'
    delete:
      summary: 终止任务
      responses:
        '200':
          description: OK
      description: 终止任务.
  '/task/{task_id}/summary':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
    get:
      summary: 获取当前任务的文章摘要.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
      description: 获取当前任务的文章摘要.
    post:
      summary: 更新当前任务的文章摘要.
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Summary'
      description: 更新当前任务的文章摘要并重新生成视频.
  '/task/{task_id}/timeline':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
    get:
      summary: 获取任务时间轴.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timeline'
      description: 获取任务时间轴.
    post:
      summary: 更新任务时间轴.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timeline'
      description: 更新任务时间轴并重新生成视频.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Timeline'
  '/task/{task_id}/upload/{filename}':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
      - schema:
          type: string
        name: filename
        in: path
    post:
      summary: 上传文件
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: file_name
                properties:
                  media_path:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        description: ''
      parameters:
        - schema: {}
          in: query
          name: file
          required: true
          description: 文件
      description: '上传文件到task中, 可以指定上传之后的文件名, 返回值为此文件在任务中的media_path'
  '/task/{task_id}/alignment':
    parameters:
      - type: string
        name: task_id
        in: path
        required: true
    get:
      summary: 返回图文对齐数据
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
      requestBody: {}
    post:
      summary: 上传图文对齐数据
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alignment'
      description: '设定图片和文字对齐数据. 注意, 上传此项将覆盖自动媒体查找和对齐过程, 完全手动设定文字和媒体. media path可以是已经上传完成的文件路径(相对), 或者URL'
    delete:
      summary: 删除手动对齐数据
      responses:
        '200':
          description: OK
      description: '删除手动对齐数据, 恢复使用自动对齐'
components:
  schemas:
    Error:
      title: Error
      type: object
      properties:
        code:
          type: integer
          description: 错误代码
        message:
          type: string
          description: 错误描述
      description: 错误
    Production_report:
      title: Production_report
      type: object
      description: 视频生成过程报告
      properties:
        start:
          type: string
          description: 生成开始时间
        end:
          type: string
          description: 结束时间
        duration:
          type: string
          description: 生成过程时长
        steps:
          type: array
          description: 生成过程每一步耗时
          items:
            type: object
            properties:
              name:
                type: string
                description: 步骤名称
              start:
                type: string
                description: 步骤开始时间
              end:
                type: string
                description: 步骤结束时间
              duration:
                type: string
                description: 步骤时长
        metadata:
          type: object
          properties:
            GIT_VERSION:
              type: string
              description: vidpress git 版本
            GIT_BRANCH:
              type: string
              description: vidpress git branch name
            API error count:
              description: api 错误个数
              type: string
            duplicated image count:
              type: string
              description: 重复图片个数
            timeline gaps count:
              type: string
              description: 时间轴空白时间段个数
            timeline gaps:
              type: array
              description: 空白时间段和相关素材
              items: {}
        start_timestamp:
          type: number
          format: float
          description: 开始时间的时间戳
        end_timestamp:
          type: number
          format: float
          description: 结束时间的时间戳
    Progress:
      title: Progress
      type: object
      properties:
        percentage:
          type: integer
          description: 0~100
        message:
          type: string
          description: 此进度描述
      description: 视频生成进度
    Summary:
      title: Summary
      type: object
      description: 生成tts的文章摘要
      properties:
        summary:
          type: string
          description: 文章摘要
      required:
        - summary
    Task_config:
      title: Task_config
      type: object
      description: 视频生成任务参数
      properties:
        news_url:
          type: string
          description: '新闻url, 目前只支持百家号url, 可以为空'
        tts_per:
          type: integer
          description: 发音人
        duration:
          type: integer
          description: '目标视频时长, 单位秒'
        callback_url:
          type: string
          description: 任务有progress时候的callback url
        priority:
          type: number
          default: 3
          description: '任务优先级, 3为普通优先级, 2为高优先级. 原则上支持1和0, 若非必要请勿占用. '
          enum:
            - 2
            - 3
          example: '3'
      required:
        - tts_per
        - duration
    Task:
      title: Task
      type: object
      description: 视频生成任务
      properties:
        id:
          type: integer
          description: task id
        config:
          $ref: '#/components/schemas/Task_config'
        status:
          oneOf:
            - description: waiting
            - description: in_progress
            - description: completed
          type: string
        estimation:
          type: object
          description: 任务时间预期
          properties:
            start_time:
              type: integer
              description: '预期的排队结束时间, 时间戳'
            finish_time:
              type: integer
              description: '预期的视频生成完成时间, 时间戳'
        progress:
          type: array
          items:
            $ref: '#/components/schemas/Progress'
        result:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/Video'
          description: '视频生产结果, 如果视频尚未生成或者生成失败此项为null'
        error:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/Error'
          description: '任务错误描述, 如果尚未有错误此项为null'
        production_report:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/Production_report'
          description: '视频生产过程报告, 包括开始结束时间, 时长, 版本信息等. 生成没有完成之前此项为null'
    Timeline:
      title: Timeline
      type: object
      description: "对时间轴的描述. 请注意, 此json中client需要关心的就是下面列出来的字段. 在tracks中有type为'audio'的, 请勿更改他们在列表中的顺序. 调整素材顺序的话请只调整type为'video'和'image'的track."
      properties:
        tracks:
          type: array
          items:
            type: object
            properties:
              media_path:
                type: string
              media_url:
                type: string
                format: uri
              start:
                type: string
              duration:
                type: number
                format: float
                example: '3.5'
              type:
                type: string
                enum:
                  - video
                  - audio
                  - image
                example: video
    Video:
      title: Video
      type: object
      description: 生成的视频
      properties:
        url:
          type: string
          description: 视频文件url
        cover_url:
          type: string
          description: ' 视频封面url'
        duration:
          type: integer
          description: '视频时长, 单位为秒'
        title:
          type: string
          description: 视频标题
        summary:
          type: string
        category:
          type: string
    Paged_tasks:
      title: Paged_tasks
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
          format: uri
          description: 下一页内容url
        previous:
          type: string
          format: uri
          description: 上一页内容url
        results:
          type: array
          items:
            $ref: ''
    Progress_callback:
      title: Progress_callback
      type: object
      description: 任务设定的callback_url中每次收到的数据格式
      properties:
        type:
          type: string
        msg:
          type: string
    Alignment:
      title: Alignment
      type: object
      properties:
        alignment:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
                description: 本段对应的文本
              media:
                type: array
                description: 'list of media path, can be either url or relative path'
                items:
                  type: string
      description: 手动媒体与文本对齐
  securitySchemes: {}
