title: Production_report
type: object
description: 视频生成过程报告
properties:
  start:
    type: string
    description: 生成开始时间
  end:
    type: string
    description: 结束时间
  duration:
    type: string
    description: 生成过程时长
  steps:
    type: array
    description: 生成过程每一步耗时
    items:
      type: object
      properties:
        name:
          type: string
          description: 步骤名称
        start:
          type: string
          description: 步骤开始时间
        end:
          type: string
          description: 步骤结束时间
        duration:
          type: string
          description: 步骤时长
  metadata:
    type: object
    properties:
      GIT_VERSION:
        type: string
        description: vidpress git 版本
      GIT_BRANCH:
        type: string
        description: vidpress git branch name
      API error count:
        type: string
        description: api 错误个数
      duplicated image count:
        type: string
        description: 重复图片个数
      timeline gaps count:
        type: string
        description: 时间轴空白时间段个数
      timeline gaps:
        type: array
        description: 空白时间段和相关素材
        items: {}
